version: "3.8"

services:
    runner:
      image: syndicatedb/github-runner:latest
      environment:
        ORGANIZATION: "your-account-or-organization"
        ACCESS_TOKEN: "RUNNER_TOKEN"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock